/**
 * Placement Statistics Model
 * 
 * @description Aggregated placement statistics for
 * analytics and reporting purposes.
 */

const mongoose = require('mongoose');

const placementStatsSchema = new mongoose.Schema({
  // Time Period
  period: {
    type: {
      type: String,
      enum: ['Daily', 'Weekly', 'Monthly', 'Yearly', 'Academic Year', 'Custom'],
      required: true
    },
    startDate: {
      type: Date,
      required: true
    },
    endDate: {
      type: Date,
      required: true
    },
    academicYear: String, // e.g., "2025-2026"
    batch: String // e.g., "2022-2026"
  },

  // Student Statistics
  studentStats: {
    totalEligible: {
      type: Number,
      default: 0
    },
    totalRegistered: {
      type: Number,
      default: 0
    },
    totalPlaced: {
      type: Number,
      default: 0
    },
    totalUnplaced: {
      type: Number,
      default: 0
    },
    totalOptedOut: {
      type: Number,
      default: 0
    },
    placementPercentage: {
      type: Number,
      default: 0
    }
  },

  // Department-wise Statistics
  departmentStats: [{
    department: String,
    totalStudents: Number,
    placedStudents: Number,
    placementPercentage: Number,
    averagePackage: Number,
    highestPackage: Number
  }],

  // Company Statistics
  companyStats: {
    totalCompaniesVisited: {
      type: Number,
      default: 0
    },
    totalCompaniesHired: {
      type: Number,
      default: 0
    },
    newCompanies: {
      type: Number,
      default: 0
    },
    returningCompanies: {
      type: Number,
      default: 0
    }
  },

  // Job Statistics
  jobStats: {
    totalJobsPosted: {
      type: Number,
      default: 0
    },
    totalOffersMade: {
      type: Number,
      default: 0
    },
    totalOffersAccepted: {
      type: Number,
      default: 0
    },
    offerAcceptanceRate: {
      type: Number,
      default: 0
    }
  },

  // Package Statistics
  packageStats: {
    highestPackage: {
      amount: {
        type: Number,
        default: 0
      },
      company: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Company'
      },
      companyName: String
    },
    lowestPackage: {
      amount: Number,
      company: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Company'
      },
      companyName: String
    },
    averagePackage: {
      type: Number,
      default: 0
    },
    medianPackage: {
      type: Number,
      default: 0
    },
    totalPackageValue: {
      type: Number,
      default: 0
    }
  },

  // Package Range Distribution
  packageDistribution: [{
    range: String, // e.g., "0-5 LPA", "5-10 LPA"
    minValue: Number,
    maxValue: Number,
    count: Number,
    percentage: Number
  }],

  // Industry-wise Distribution
  industryDistribution: [{
    industry: String,
    companiesCount: Number,
    studentsPlaced: Number,
    averagePackage: Number
  }],

  // Monthly Trend (for yearly stats)
  monthlyTrend: [{
    month: String,
    year: Number,
    companiesVisited: Number,
    offersReceived: Number,
    studentsPlaced: Number,
    averagePackage: Number
  }],

  // Top Recruiters
  topRecruiters: [{
    company: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Company'
    },
    companyName: String,
    studentsHired: Number,
    averagePackage: Number,
    highestPackage: Number
  }],

  // Skill Demand Analysis
  skillDemand: [{
    skill: String,
    demandCount: Number, // Number of jobs requiring this skill
    successRate: Number // Percentage of students with this skill who got placed
  }],

  // Comparison with Previous Period
  comparison: {
    previousPeriod: {
      placementPercentage: Number,
      averagePackage: Number,
      companiesVisited: Number
    },
    percentageChange: {
      placementPercentage: Number,
      averagePackage: Number,
      companiesVisited: Number
    }
  },

  // Generated by
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  lastUpdatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  
  // Auto-refresh settings
  autoRefresh: {
    type: Boolean,
    default: true
  },
  refreshInterval: {
    type: String,
    enum: ['Hourly', 'Daily', 'Weekly'],
    default: 'Daily'
  },
  lastRefreshed: Date

}, {
  timestamps: true
});

// Indexes
placementStatsSchema.index({ 'period.type': 1, 'period.startDate': 1 });
placementStatsSchema.index({ 'period.academicYear': 1 });
placementStatsSchema.index({ 'period.batch': 1 });

// Static method to get or create current stats
placementStatsSchema.statics.getCurrentStats = async function(academicYear) {
  let stats = await this.findOne({ 'period.academicYear': academicYear });
  
  if (!stats) {
    stats = new this({
      period: {
        type: 'Academic Year',
        startDate: new Date(`${academicYear.split('-')[0]}-07-01`),
        endDate: new Date(`${academicYear.split('-')[1]}-06-30`),
        academicYear
      }
    });
    await stats.save();
  }
  
  return stats;
};

// Method to recalculate all statistics
placementStatsSchema.methods.recalculate = async function() {
  const Application = mongoose.model('Application');
  const StudentProfile = mongoose.model('StudentProfile');
  const Company = mongoose.model('Company');
  const JobPosting = mongoose.model('JobPosting');

  // This is a complex aggregation - simplified version
  const startDate = this.period.startDate;
  const endDate = this.period.endDate;

  // Get placed students count
  const placedStudents = await StudentProfile.countDocuments({
    placementStatus: 'Placed',
    updatedAt: { $gte: startDate, $lte: endDate }
  });

  const totalStudents = await StudentProfile.countDocuments({
    isVerified: true
  });

  this.studentStats.totalPlaced = placedStudents;
  this.studentStats.totalEligible = totalStudents;
  this.studentStats.placementPercentage = totalStudents > 0 
    ? ((placedStudents / totalStudents) * 100).toFixed(2) 
    : 0;

  // Get company stats
  const companiesVisited = await Company.countDocuments({
    isApproved: true,
    approvedAt: { $gte: startDate, $lte: endDate }
  });

  this.companyStats.totalCompaniesVisited = companiesVisited;

  // Get job stats
  const totalJobs = await JobPosting.countDocuments({
    createdAt: { $gte: startDate, $lte: endDate }
  });

  this.jobStats.totalJobsPosted = totalJobs;

  // Get package stats
  const packageAgg = await Application.aggregate([
    {
      $match: {
        status: 'Selected',
        updatedAt: { $gte: startDate, $lte: endDate }
      }
    },
    {
      $lookup: {
        from: 'jobpostings',
        localField: 'job',
        foreignField: '_id',
        as: 'jobDetails'
      }
    },
    { $unwind: '$jobDetails' },
    {
      $group: {
        _id: null,
        avgPackage: { $avg: '$jobDetails.package.ctc' },
        maxPackage: { $max: '$jobDetails.package.ctc' },
        minPackage: { $min: '$jobDetails.package.ctc' },
        totalPackage: { $sum: '$jobDetails.package.ctc' }
      }
    }
  ]);

  if (packageAgg.length > 0) {
    this.packageStats.averagePackage = packageAgg[0].avgPackage || 0;
    this.packageStats.highestPackage.amount = packageAgg[0].maxPackage || 0;
    this.packageStats.lowestPackage.amount = packageAgg[0].minPackage || 0;
    this.packageStats.totalPackageValue = packageAgg[0].totalPackage || 0;
  }

  this.lastRefreshed = new Date();
  await this.save();
};

module.exports = mongoose.model('PlacementStats', placementStatsSchema);
